### ISSUE TITLE
clean toolchain build fails

### ISSUE THREAD

**Issue by flopsi** [t-crest/patmos-misc#7] opened 2016-01-20 19:59 UTC
A clean toolchain build (-o option of build.sh) fails due to a wrong ordering of building targets. The patmos target is built before newlib, which causes an error when compiling the bootloader.

In comparison to the option to build all targets (-a) there are two differences. Firstly, the pasim target is built instead of the patmos target. Secondly, newlib and compiler-rt are built before the pasim target.

Does anyone have strong feelings about building pasim instead of patmos and building the system libraries first for a toolchain build?

**Comment by schoeberl** [comment] 2016-01-20 22:06
We do nightly regression tests on building the whole T-CREST project from source.
Everyone can add him/herself to receive an email in misc/recipients.txt

That clean build has no order issue. Builds the compiler before Patmos.

Martin

**Comment by flopsi** [comment] 2016-01-25 13:27
The buildbot again builds the targets in a a different order -- it is somewhat like "build.sh -o", except that it  builds pasim instead of patmos. Patmos is later built and synthesized separately.

Note that the error does not appear when you locally do a "make clean" of all builds on a machine with the tool chain installed. You also have to remove the installed files to trigger the error.

Also note that it is not an issue with building the compiler, it is a library issue (newlib and compiler-rt).


If there are no objections, I will simply change the tool chain build (-o) to only build pasim.

**Comment by jeuneS2** [comment] 2016-01-25 14:16
On 2016-01-25 14:27, flopsi wrote:
> The buildbot again builds the targets in a a different order -- it is
> somewhat like "build.sh -o", except that it builds pasim instead of
> patmos. Patmos is later built and synthesized separately.

Unless something has changed recently, the build targets pasim and
patmos do exactly the same thing. In my opinion, the "pasim" target
should be removed so we have a single target "patmos".

> Note that the error does not appear when you locally do a "make clean"
> of all builds on a machine with the tool chain installed. You also have
> to remove the installed files to trigger the error.
> 
> Also note that it is not an issue with building the compiler, it is a
> library issue (newlib and compiler-rt).
> 
> If there are no objections, I will simply change the tool chain build
> (-o) to only build pasim.

I would prefer to change the build order rather than changing what is
being built. Building only pasim but not the emulator would mean that
the latter would not be tested against the tool chain.

**Comment by flopsi** [comment] 2016-01-25 14:49
Hi Wolfgang,

pasim and patmos used to be different -- one only built the simulator the other also the hardware-related parts. but it seems that this has changed. sorry my bad.

I do agree, given that both do the same thing, it would be better to remove the pasim target. Consequently, the only option to fix the original issue is to fix the build order. I'll send you a patch.

**Comment by Emoun** [comment] 2020-05-18 09:48
Closing this issue because it is so old. I'm not sure whether it is still relevant, but clearly no one is bothered by this anymore, or not bothered enough to do anything about it.

**Closed by Emoun** 2020-05-18 09:48 UTC
